### ISSUE TITLE
MinAuthorities is not checked on auto removal

### ISSUE THREAD

**Issue by davxy** [gautamdhameja/substrate-validator-set#32]
The constraint is checked only on `do_remove_validator`, that is called by the `remove_validator` extrinsic.

Shouldn't the constraint be respected on `remove_offline_validators` as well?

**Comment by gautamdhameja** [comment]
That's because `remove_offline_validators` is called in the session change hook and removes the validators who reported offline during the session that is ending. Even if we put the check of `MinAuthorithies` here, the offline validators that are not removed (because of this check) will not produce blocks and will have the same overall effect on the runtime. 

The `MinAuthorithies` check is to not go below the threshold when manually removing healthy validators. Makes sense?

**Comment by davxy** [comment]
Yes, it makes sense. Thank you

**Comment by korol-sas** [comment]
Same problem when initializing genesis

Error:
```
Thread 'main' panicked at 'At least 2 validators should be initialized', /home/dev/.cargo/git/checkouts/substrate-validator-set-f1aaacaa79a24970/91375ae/src/lib.rs:172
```

Code:
```rust
assert!(validators.len() > 1, "At least 2 validators should be initialized");
```
https://github.com/gautamdhameja/substrate-validator-set/blob/master/src/lib.rs#L172

**Comment by korol-sas** [comment]
My MR to the fix problem:

https://github.com/gautamdhameja/substrate-validator-set/pull/34
